version: "3"
services:

  hnn:
    image: jonescompneurolab/hnn
    container_name: hnn_container
    hostname: hnn-container
    ports:
      - "22"
    environment:
      XAUTHORITY: "/home/hnn_user/.Xauthority"
      DISPLAY: "host.docker.internal:0"
    volumes:
      - "$XAUTHORITY:/home/hnn_user/.Xauthority"
      - "./docker_hnn_out:/home/hnn_user/hnn_out"
    command: "sudo /start_ssh.sh"
